## stock-market-tracker/stock_processor/stock_pb2.py

# Generated by the protocol buffer compiler. DO NOT EDIT!
# Source: stock.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name="stock.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0bstock.proto\"\x1c\n\x0cStockRequest\x12\x0c\n\x04symbol\x18\x01 \x01(\t\"\'\n\rStockResponse\x12\x0c\n\x04symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x32\x36\n\x0cStockService\x12&\n\x08GetStock\x12\r.StockRequest\x1a\x0e.StockResponse\"\x00\x62\x06proto3',
)

_STOCKREQUEST = _descriptor.Descriptor(
    name="StockRequest",
    full_name="StockRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="symbol",
            full_name="StockRequest.symbol",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value="".encode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    serialized_start=15,
    serialized_end=43,
)

_STOCKRESPONSE = _descriptor.Descriptor(
    name="StockResponse",
    full_name="StockResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="symbol",
            full_name="StockResponse.symbol",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value="".encode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="price",
            full_name="StockResponse.price",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=0.0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    serialized_start=45,
    serialized_end=84,
)

DESCRIPTOR.message_types_by_name["StockRequest"] = _STOCKREQUEST
DESCRIPTOR.message_types_by_name["StockResponse"] = _STOCKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockRequest = _reflection.GeneratedProtocolMessageType(
    "StockRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _STOCKREQUEST,
        "__module__": "stock_pb2",
    },
)
_sym_db.RegisterMessage(StockRequest)

StockResponse = _reflection.GeneratedProtocolMessageType(
    "StockResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _STOCKRESPONSE,
        "__module__": "stock_pb2",
    },
)
_sym_db.RegisterMessage(StockResponse)
