# Generated by the protocol buffer compiler. DO NOT EDIT!

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name="stock.proto",
    package="stock_processor",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x0bstock.proto\x12\x0estock_processor\"\x1c\n\x0cStockRequest\x12\x0c\n\x04symbol\x18\x01 \x01(\t\"\'\n\rStockResponse\x12\x0c\n\x04symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x32G\n\x0cStockService\x12\x37\n\x08GetStock\x12\x16.stock_processor.StockRequest\x1a\x17.stock_processor.StockResponse\"\x00b\x06proto3'
)

# Define StockRequest message
class StockRequest(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _descriptor.Descriptor(
        name="StockRequest",
        full_name="stock_processor.StockRequest",
        fields=[
            _descriptor.FieldDescriptor(
                name="symbol",
                full_name="stock_processor.StockRequest.symbol",
                index=0,
                number=1,
                type=9,
                cpp_type=9,
                label=1,
                has_default_value=False,
                default_value="",
                containing_type=None,
                serialized_options=None,
            ),
        ],
    )
    __module__ = "stock_pb2"

# Define StockResponse message
class StockResponse(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _descriptor.Descriptor(
        name="StockResponse",
        full_name="stock_processor.StockResponse",
        fields=[
            _descriptor.FieldDescriptor(
                name="symbol",
                full_name="stock_processor.StockResponse.symbol",
                index=0,
                number=1,
                type=9,
                cpp_type=9,
                label=1,
                has_default_value=False,
                default_value="",
                containing_type=None,
                serialized_options=None,
            ),
            _descriptor.FieldDescriptor(
                name="price",
                full_name="stock_processor.StockResponse.price",
                index=1,
                number=2,
                type=2,
                cpp_type=6,
                label=1,
                has_default_value=False,
                default_value=0.0,
                containing_type=None,
                serialized_options=None,
            ),
        ],
    )
    __module__ = "stock_pb2"

_sym_db.RegisterMessage(StockRequest)
_sym_db.RegisterMessage(StockResponse)
