version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - mongo

  stock_fetcher:
    build: ./stock_fetcher
    depends_on:
      - kafka

  stock_processor:
    build: ./stock_processor
    ports:
      - "50051:50051"
    depends_on:
      - kafka
      - mongo

volumes:
  mongo_data:
