version: '3.8'
services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
  stock_fetcher:
    build: ./stock_fetcher
  stock_processor:
    build: ./stock_processor
    ports:
      - "50051:50051"
  kafka:
    image: wurstmeister/kafka
  mongo:
    image: mongo