## stock-market-tracker/deployments/k8s-service.yml

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: stock-market-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: stock-processor-service
spec:
  selector:
    app: stock-market-tracker
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: stock-market-tracker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: stock-market-tracker
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
