apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Updated to match API Gateway container port
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: stock-processor-service
spec:
  selector:
    app: stock-processor
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: NodePort  # Changed from ClusterIP to NodePort for external access

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
